boost_version: "1_82_0"
boost_root: "../boost_1_82_0"
crawlers:
  - name: AsciiDoc
    libraries:
      - assert
      - container_hash
      - describe
      - endian
      - io
      - lambda2
      - leaf
      - mp11
      - predef
      - qvm
      - smart_ptr
      - system
      - throw_exception
      - unordered
      - variant2

  - name: QuickBook
    libraries:
      - accumulators
      - algorithm
      - align
      - any
      - array
      - asio
      - atomic
      - beast
      - bimap
      - bind
      - callable_traits
      - chrono
      - circular_buffer
      - compute
      - config
      - container
      - context
      - contract
      - conversion
      - convert
      - core
      - coroutine
      - coroutine2
      - crc
      - date_time
      - detail
      - dll
      - fiber
      - foreach
      - function_types
      - function
      - fusion
      - geometry
      - graph
      - heap
      - histogram
      - hof
      - icl
      - integer
      - interprocess
      - intrusive
      - json
      - lambda
      - lexical_cast
      - local_function
      - lockfree
      - log
      - math
      - metaparse
      - move
      - mpi
      - msm
      - multi_array
      - multiprecision
      - mysql
      - optional
      - pfr
      - phoenix
      - poly_collection
      - pool
      - process
      - program_options
      - property_tree
      - proto
      - python
      - random
      - range
      - ratio
      - regex
      - safe_numerics
      - scope_exit
      - signals2
      - sort
      - spirit
      - stacktrace
      - static_assert
      - static_string
      - stl_interfaces
      - test
      - thread
      - tribool
      - tti
      - tuple
      - type_erasure
      - type_index
      - type_traits
      - typeof
      - units
      - url
      - utility
      - variant
      - vmd
      - winapi
      - xpressive
      - yap
